window.CAREER_DATA = {
  startTypes:[
    {id:'open',title:'아직 잘 모르겠어요',desc:'재미있게 했던 경험부터 찾아봅니다.'},
    {id:'interest',title:'관심 분야가 있어요',desc:'관심 분야가 실제 경험과 연결되는지 확인합니다.'},
    {id:'job',title:'희망 직업이 있어요',desc:'그 직업의 실제 업무와 환경을 비교합니다.'}
  ],
  experienceAreas:[
    {id:'initiative',label:'스스로 시작한 경험',icon:'🚀'},
    {id:'flow',label:'시간 가는 줄 모르고 한 경험',icon:'⏱️'},
    {id:'help',label:'다른 사람을 도운 경험',icon:'🤝'},
    {id:'solve',label:'문제를 해결하거나 방법을 바꾼 경험',icon:'🧩'},
    {id:'research',label:'자료를 조사·정리·비교한 경험',icon:'🔎'},
    {id:'create',label:'만들거나 설명하거나 표현한 경험',icon:'🛠️'}
  ],
  starterExamples:[
    '모둠 발표에서 자료가 너무 많아 핵심만 골라 순서를 다시 정했다.',
    '친구가 어려워하는 교과 개념을 그림이나 쉬운 말로 설명했다.',
    '게임이나 운동에서 잘 안 되던 방법을 바꾸어 다시 시도했다.',
    '관심 있는 주제의 영상·기사·자료를 찾아 서로 비교했다.',
    '교실이나 집에서 불편한 점을 발견하고 더 나은 방법을 생각했다.',
    '포스터·영상·발표자료·그림·글 등으로 내 생각을 표현했다.'
  ],
  actions:[
    {id:'research',label:'조사하기',desc:'필요한 자료나 정보를 찾아봄',group:'탐색'},
    {id:'compare',label:'비교하기',desc:'둘 이상의 자료에서 차이와 공통점을 찾음',group:'탐색'},
    {id:'analyze',label:'분석하기',desc:'왜 그런지 원인·구조·의미를 살펴봄',group:'탐색'},
    {id:'organize',label:'정리하기',desc:'핵심을 골라 순서나 체계를 세움',group:'구성·제작'},
    {id:'design',label:'설계하기',desc:'목표에 맞게 방법·구조·흐름을 계획함',group:'구성·제작'},
    {id:'make',label:'만들기',desc:'아이디어를 실제 결과물로 구현함',group:'구성·제작'},
    {id:'explain',label:'설명하기',desc:'상대가 이해하도록 쉽게 풀어 말함',group:'전달'},
    {id:'express',label:'표현하기',desc:'글·그림·영상·말 등으로 생각을 드러냄',group:'전달'},
    {id:'persuade',label:'설득하기',desc:'근거를 들어 다른 사람의 판단을 돕거나 움직임',group:'전달'},
    {id:'help',label:'돕기',desc:'다른 사람의 어려움을 파악하고 지원함',group:'협력·개선'},
    {id:'coordinate',label:'조정하기',desc:'역할·일정·의견을 맞추어 흐름을 만듦',group:'협력·개선'},
    {id:'revise',label:'수정하기',desc:'오류나 피드백을 반영해 더 나아지게 함',group:'협력·개선'}
  ],
  hypotheses:[
    {actions:['research','compare','analyze'],text:'여러 자료에서 차이와 근거를 찾는 활동에 강점 가능성이 있습니다.'},
    {actions:['organize','explain','help'],text:'복잡한 내용을 상대가 이해하기 쉽게 바꾸어 전달하는 경향이 있습니다.'},
    {actions:['design','make','revise'],text:'아이디어를 결과물로 만들고 개선하는 과정에 관심이 나타납니다.'},
    {actions:['organize','coordinate','revise'],text:'역할과 흐름을 정돈하고 실행을 돕는 행동이 반복됩니다.'},
    {actions:['express','persuade','make'],text:'생각을 인상적으로 표현하고 전달하는 활동에 관심이 나타납니다.'},
    {actions:['help','explain','coordinate'],text:'사람의 어려움을 파악하고 설명·조정하며 돕는 행동이 나타납니다.'}
  ],
  preferredActions:[
    {id:'analyze',label:'원인 찾기'}, {id:'design',label:'새롭게 설계하기'}, {id:'make',label:'실제로 만들기'},
    {id:'explain',label:'쉽게 설명하기'}, {id:'help',label:'사람을 돕기'}, {id:'research',label:'자료를 조사하기'},
    {id:'express',label:'생각을 표현하기'}, {id:'coordinate',label:'역할과 일을 조정하기'}
  ],
  targets:[
    {id:'people',label:'사람'}, {id:'language',label:'글과 언어'}, {id:'data',label:'숫자와 데이터'},
    {id:'machine',label:'기계와 사물'}, {id:'nature',label:'자연과 생명'}, {id:'society',label:'사회문제'},
    {id:'content',label:'이미지와 콘텐츠'}, {id:'ideas',label:'아이디어와 지식'}
  ],
  environments:[
    {id:'social',left:'혼자 집중하기',right:'사람들과 함께하기'},
    {id:'structure',left:'정해진 기준',right:'자유로운 방식'},
    {id:'pace',left:'조용하고 안정적',right:'변화가 빠르고 활동적'},
    {id:'place',left:'실내 중심',right:'현장 중심'},
    {id:'time',left:'빠른 결과 확인',right:'오랜 기간 결과 만들기'}
  ],
  subjects:['국어','수학','영어','사회','과학','정보','예술','체육','기술·가정','진로·융합'],
  jobs:[
    {id:'teacher',name:'교사',actions:['explain','help','coordinate'],targets:['people','ideas'],env:{social:4,structure:3,pace:3,place:2,time:3},problem:'학생이 개념을 이해하고 성장하도록 돕습니다.',tasks:['수업 설계와 설명','학습 과정 관찰','피드백과 생활지도'],hard:'많은 학생을 동시에 지원하고 꾸준히 준비해야 합니다.',majors:['교육·사범계열'],subjects:['국어','수학','사회','과학','영어','진로·융합'],club:'학습나눔·토론·교육봉사 성격',source:'공식 직업정보 확인 권장'},
    {id:'educontent',name:'교육 콘텐츠 기획자',actions:['organize','explain','design'],targets:['people','content','ideas'],env:{social:3,structure:3,pace:4,place:1,time:3},problem:'어려운 지식을 이해하기 쉬운 학습 콘텐츠로 바꿉니다.',tasks:['학습자 분석','콘텐츠 구조 설계','사용자 피드백 반영'],hard:'교육 효과와 재미를 동시에 맞춰야 합니다.',majors:['교육공학·교육·콘텐츠·디자인'],subjects:['국어','정보','예술','진로·융합'],club:'미디어·교육·콘텐츠 제작 성격',source:'일반적 경향'},
    {id:'data',name:'데이터 분석가',actions:['research','compare','analyze'],targets:['data','society'],env:{social:2,structure:4,pace:3,place:1,time:4},problem:'데이터에서 의미와 의사결정 근거를 찾습니다.',tasks:['자료 정리','패턴 분석','결과 시각화와 설명'],hard:'정확성을 위해 반복 검토와 긴 집중이 필요합니다.',majors:['통계·수학·컴퓨터·경영'],subjects:['수학','정보','사회'],club:'데이터·통계·코딩 성격',source:'공식 직업정보 확인 권장'},
    {id:'policy',name:'정책 연구원',actions:['research','analyze','persuade'],targets:['society','data','language'],env:{social:3,structure:4,pace:2,place:2,time:5},problem:'사회문제의 원인을 분석하고 정책 대안을 제안합니다.',tasks:['자료 조사','이해관계 분석','보고서와 대안 작성'],hard:'결과가 실제 변화로 이어지는 데 시간이 오래 걸릴 수 있습니다.',majors:['행정·정치외교·경제·사회'],subjects:['사회','국어','수학'],club:'사회문제·토론·시사탐구 성격',source:'일반적 경향'},
    {id:'journalist',name:'기자·콘텐츠 저널리스트',actions:['research','compare','express'],targets:['society','language','people'],env:{social:4,structure:2,pace:5,place:4,time:1},problem:'사실을 확인하고 사회에 필요한 정보를 전달합니다.',tasks:['취재','자료 검증','기사·영상 제작'],hard:'시간 압박과 정보 정확성 책임이 큽니다.',majors:['언론·미디어·국어·사회'],subjects:['국어','사회','정보'],club:'신문·방송·미디어 성격',source:'공식 직업정보 확인 권장'},
    {id:'ux',name:'UX·서비스 기획자',actions:['research','design','revise'],targets:['people','content','ideas'],env:{social:4,structure:2,pace:4,place:2,time:3},problem:'사람이 제품이나 서비스를 더 편리하게 사용하도록 설계합니다.',tasks:['사용자 조사','화면·이용 흐름 설계','테스트와 개선'],hard:'서로 다른 요구를 조정하고 여러 번 수정해야 합니다.',majors:['디자인·경영·심리·컴퓨터'],subjects:['정보','예술','사회','진로·융합'],club:'디자인·창업·앱기획 성격',source:'일반적 경향'},
    {id:'developer',name:'소프트웨어 개발자',actions:['analyze','design','make'],targets:['ideas','data','machine'],env:{social:2,structure:3,pace:4,place:1,time:4},problem:'문제를 해결하는 프로그램과 디지털 기능을 만듭니다.',tasks:['요구 분석','코드 작성','오류 수정'],hard:'오류를 오래 추적하고 새로운 기술을 계속 배워야 합니다.',majors:['컴퓨터·소프트웨어·정보통신'],subjects:['정보','수학','과학'],club:'코딩·메이커 성격',source:'공식 직업정보 확인 권장'},
    {id:'robotics',name:'로봇공학자',actions:['analyze','design','make'],targets:['machine','data'],env:{social:3,structure:4,pace:3,place:3,time:5},problem:'사람을 돕는 자동화 기계와 로봇 시스템을 개발합니다.',tasks:['기구·회로 설계','센서와 제어 실험','성능 개선'],hard:'수학·과학 개념과 반복 실험이 많이 필요합니다.',majors:['기계·전자·로봇·컴퓨터'],subjects:['수학','과학','정보','기술·가정'],club:'과학탐구·로봇·메이커 성격',source:'공식 직업정보 확인 권장'},
    {id:'bioresearch',name:'생명과학 연구원',actions:['research','analyze','revise'],targets:['nature','data'],env:{social:2,structure:5,pace:2,place:3,time:5},problem:'생명 현상의 원리를 밝히고 새로운 해결 방법을 찾습니다.',tasks:['가설 설정','실험과 측정','결과 해석'],hard:'결과가 예상과 다르거나 오랜 반복 실험이 필요할 수 있습니다.',majors:['생명과학·생명공학·바이오'],subjects:['과학','수학','정보'],club:'생명과학·실험탐구 성격',source:'공식 직업정보 확인 권장'},
    {id:'environment',name:'환경 분석·연구원',actions:['research','analyze','persuade'],targets:['nature','society','data'],env:{social:3,structure:4,pace:2,place:4,time:5},problem:'환경 문제를 측정·분석하고 개선 방안을 제안합니다.',tasks:['현장 조사','데이터 분석','보고서와 대안 작성'],hard:'현장 조건이 다양하고 변화가 천천히 나타날 수 있습니다.',majors:['환경·생태·지구과학·화학'],subjects:['과학','수학','사회'],club:'환경·생태·과학탐구 성격',source:'일반적 경향'},
    {id:'psych',name:'심리 연구·상담 분야',actions:['research','help','explain'],targets:['people','data','ideas'],env:{social:5,structure:4,pace:2,place:2,time:4},problem:'사람의 생각과 행동을 이해하고 적절한 도움을 찾습니다.',tasks:['관찰·검사·면담','자료 해석','지원 계획 수립'],hard:'감정적으로 어려운 이야기를 듣고 전문 자격 과정이 필요할 수 있습니다.',majors:['심리·상담·교육'],subjects:['사회','과학','국어'],club:'또래상담·심리탐구 성격',source:'직무·자격 경로 추가 확인 필요'},
    {id:'socialworker',name:'사회복지사',actions:['help','coordinate','explain'],targets:['people','society'],env:{social:5,structure:4,pace:4,place:4,time:3},problem:'도움이 필요한 사람이 필요한 자원과 서비스를 이용하도록 지원합니다.',tasks:['상담과 욕구 파악','서비스 연결','사례 기록과 협업'],hard:'다양한 상황을 조정하며 감정적 부담을 느낄 수 있습니다.',majors:['사회복지·아동·노인복지'],subjects:['사회','국어','진로·융합'],club:'봉사·상담·지역사회 성격',source:'공식 자격 정보 확인 필요'},
    {id:'nurse',name:'간호사',actions:['help','analyze','coordinate'],targets:['people','nature'],env:{social:5,structure:5,pace:5,place:3,time:2},problem:'환자의 상태를 관찰하고 치료와 회복을 지원합니다.',tasks:['상태 관찰','간호 수행','의료진과 협업'],hard:'교대근무·긴장 상황·정확한 판단 부담이 있을 수 있습니다.',majors:['간호학'],subjects:['과학','체육','사회'],club:'보건·생명과학·봉사 성격',source:'공식 면허·직업정보 확인 필요'},
    {id:'doctor',name:'의사',actions:['analyze','help','explain'],targets:['people','nature','data'],env:{social:4,structure:5,pace:5,place:3,time:4},problem:'질병을 진단하고 치료 방법을 결정합니다.',tasks:['진료와 검사 해석','치료 결정','환자 설명'],hard:'긴 교육 과정과 높은 책임, 긴급 상황 대응이 필요합니다.',majors:['의학'],subjects:['과학','수학','국어'],club:'의생명·과학탐구·봉사 성격',source:'공식 교육·면허 정보 확인 필요'},
    {id:'pharmacist',name:'약사',actions:['analyze','explain','organize'],targets:['people','nature','data'],env:{social:4,structure:5,pace:3,place:1,time:2},problem:'의약품을 안전하고 적절하게 사용하도록 돕습니다.',tasks:['조제와 검토','복약 안내','의약품 관리'],hard:'작은 오류도 큰 영향을 줄 수 있어 정확성이 매우 중요합니다.',majors:['약학'],subjects:['과학','수학'],club:'화학·생명과학 탐구 성격',source:'공식 면허·교육 정보 확인 필요'},
    {id:'architect',name:'건축가',actions:['design','make','coordinate'],targets:['machine','people','ideas'],env:{social:4,structure:4,pace:3,place:4,time:5},problem:'사람이 사용하는 공간을 안전하고 의미 있게 설계합니다.',tasks:['공간 설계','도면·모형 제작','공사 관계자 협의'],hard:'안전·법규·예산·미적 요구를 함께 맞춰야 합니다.',majors:['건축학·건축공학'],subjects:['수학','과학','예술','기술·가정'],club:'건축·미술·메이커 성격',source:'공식 자격 경로 확인 필요'},
    {id:'industrial',name:'제품·산업디자이너',actions:['design','make','revise'],targets:['machine','content','people'],env:{social:3,structure:2,pace:4,place:2,time:3},problem:'사용하기 편하고 매력적인 제품의 형태와 경험을 설계합니다.',tasks:['사용자 조사','아이디어 스케치','모형 제작과 수정'],hard:'미적 판단과 현실적인 생산 조건을 함께 고려해야 합니다.',majors:['산업디자인·제품디자인'],subjects:['예술','기술·가정','정보'],club:'디자인·메이커 성격',source:'일반적 경향'},
    {id:'graphic',name:'시각·그래픽디자이너',actions:['express','design','revise'],targets:['content','language','ideas'],env:{social:3,structure:2,pace:4,place:1,time:2},problem:'정보와 메시지를 시각적으로 이해하기 쉽게 전달합니다.',tasks:['콘셉트 기획','그래픽 제작','피드백 반영'],hard:'수정 요청과 마감 압박이 잦을 수 있습니다.',majors:['시각디자인·콘텐츠디자인'],subjects:['예술','정보','국어'],club:'미술·미디어·디자인 성격',source:'일반적 경향'},
    {id:'video',name:'영상 콘텐츠 기획·제작자',actions:['research','express','coordinate'],targets:['content','people','society'],env:{social:4,structure:2,pace:5,place:4,time:2},problem:'정보나 이야기를 영상으로 구성해 전달합니다.',tasks:['주제·스토리 기획','촬영·편집','출연자·일정 조정'],hard:'마감과 협업 변수가 많고 반복 수정이 필요합니다.',majors:['미디어·영상·방송·콘텐츠'],subjects:['국어','예술','정보','사회'],club:'방송·영상·미디어 성격',source:'일반적 경향'},
    {id:'writer',name:'작가·스토리 기획자',actions:['research','express','revise'],targets:['language','ideas','people'],env:{social:1,structure:2,pace:2,place:1,time:5},problem:'경험과 아이디어를 이야기와 글로 만들어 전달합니다.',tasks:['자료 조사','구성·집필','퇴고와 수정'],hard:'혼자 오래 집중하며 불확실한 평가를 견뎌야 할 수 있습니다.',majors:['문예창작·국어국문·콘텐츠'],subjects:['국어','사회','예술'],club:'독서·문예·콘텐츠 성격',source:'일반적 경향'},
    {id:'translator',name:'번역·통역 분야',actions:['analyze','explain','express'],targets:['language','people','ideas'],env:{social:3,structure:4,pace:4,place:2,time:2},problem:'서로 다른 언어와 문화의 의미를 정확하게 전달합니다.',tasks:['원문 이해','의미 재구성','용어와 맥락 검토'],hard:'높은 언어 정확성과 빠른 판단이 요구될 수 있습니다.',majors:['언어·통번역·국제학'],subjects:['영어','국어','사회'],club:'외국어·국제교류 성격',source:'일반적 경향'},
    {id:'lawyer',name:'법률가',actions:['research','analyze','persuade'],targets:['people','society','language'],env:{social:4,structure:5,pace:4,place:2,time:4},problem:'법률을 적용해 분쟁을 해결하고 권리를 보호합니다.',tasks:['사실·법령 조사','논리 구성','상담과 주장'],hard:'복잡한 자료와 높은 책임, 긴 준비 과정이 필요합니다.',majors:['법학·다양한 학부 후 전문과정'],subjects:['사회','국어','영어'],club:'토론·모의법정·사회탐구 성격',source:'공식 자격·교육 경로 확인 필요'},
    {id:'marketing',name:'마케팅 기획자',actions:['research','persuade','design'],targets:['people','data','content'],env:{social:4,structure:2,pace:5,place:2,time:2},problem:'사람이 제품·서비스의 가치를 이해하고 선택하도록 전략을 만듭니다.',tasks:['시장·고객 조사','캠페인 기획','성과 분석'],hard:'빠르게 변하는 반응과 성과 압박을 다뤄야 합니다.',majors:['경영·광고홍보·심리·데이터'],subjects:['사회','수학','국어','정보'],club:'창업·광고·미디어 성격',source:'일반적 경향'},
    {id:'accountant',name:'회계·재무 전문가',actions:['organize','analyze','revise'],targets:['data','society'],env:{social:2,structure:5,pace:3,place:1,time:3},problem:'조직의 돈과 거래 정보를 정확하게 기록·분석합니다.',tasks:['자료 검토','재무 분석','오류 확인과 보고'],hard:'세밀한 정확성과 마감 시기 집중 업무가 필요합니다.',majors:['회계·경영·경제'],subjects:['수학','사회','정보'],club:'경제·경영·금융 성격',source:'자격 경로 추가 확인 필요'},
    {id:'entrepreneur',name:'창업·서비스 운영자',actions:['design','coordinate','persuade'],targets:['people','ideas','society'],env:{social:5,structure:1,pace:5,place:3,time:4},problem:'새로운 문제 해결 방식이나 서비스를 만들어 운영합니다.',tasks:['문제 발견','서비스 기획','사람·자원·일정 조정'],hard:'불확실성과 책임, 실패 가능성을 감수해야 합니다.',majors:['전공 제한 적음·경영·기술·디자인 등'],subjects:['사회','정보','국어','진로·융합'],club:'창업·프로젝트·학생자치 성격',source:'일반적 경향'},
    {id:'mechanical',name:'기계공학자',actions:['analyze','design','make'],targets:['machine','data'],env:{social:3,structure:5,pace:3,place:3,time:5},problem:'기계와 장치가 안전하고 효율적으로 작동하도록 설계합니다.',tasks:['원리 계산','설계·모델링','시험과 개선'],hard:'수학·물리 개념과 세밀한 검증이 필요합니다.',majors:['기계공학·자동차·항공'],subjects:['수학','과학','정보','기술·가정'],club:'메이커·로봇·과학탐구 성격',source:'공식 직업정보 확인 권장'},
    {id:'electrical',name:'전기·전자공학자',actions:['analyze','design','revise'],targets:['machine','data'],env:{social:3,structure:5,pace:4,place:3,time:5},problem:'전기·전자 시스템과 기기가 안정적으로 작동하도록 개발합니다.',tasks:['회로·시스템 설계','측정과 시험','오류 개선'],hard:'안전과 정확성이 중요하고 기술 변화가 빠릅니다.',majors:['전기·전자·반도체·정보통신'],subjects:['수학','과학','정보'],club:'전자·로봇·메이커 성격',source:'공식 직업정보 확인 권장'},
    {id:'chemist',name:'화학 연구원',actions:['research','analyze','revise'],targets:['nature','data'],env:{social:2,structure:5,pace:2,place:3,time:5},problem:'물질의 성질과 변화를 연구해 새로운 소재와 방법을 찾습니다.',tasks:['실험 설계','측정과 분석','안전 관리와 개선'],hard:'반복 실험과 안전 수칙 준수가 필수입니다.',majors:['화학·화학공학·신소재'],subjects:['과학','수학'],club:'화학·과학탐구 성격',source:'공식 직업정보 확인 권장'},
    {id:'food',name:'식품 연구·개발자',actions:['research','design','revise'],targets:['nature','people','data'],env:{social:3,structure:5,pace:3,place:3,time:4},problem:'안전하고 맛있으며 기능적인 식품을 개발합니다.',tasks:['원료 조사','제품 실험','품질·소비자 반응 분석'],hard:'위생·안전 기준과 반복 시험을 맞춰야 합니다.',majors:['식품영양·식품공학·생명'],subjects:['과학','수학','기술·가정'],club:'식품·생명·과학탐구 성격',source:'일반적 경향'},
    {id:'sports',name:'스포츠 지도·분석 분야',actions:['help','analyze','coordinate'],targets:['people','data'],env:{social:5,structure:3,pace:5,place:5,time:2},problem:'운동 능력과 건강을 향상시키도록 지도하고 분석합니다.',tasks:['훈련 지도','동작·기록 분석','프로그램 조정'],hard:'신체 활동과 사람별 차이를 지속적으로 관리해야 합니다.',majors:['체육·스포츠과학·건강'],subjects:['체육','과학','수학'],club:'스포츠·건강·데이터 성격',source:'자격·직무별 추가 확인 필요'},
    {id:'urban',name:'도시·교통 기획자',actions:['research','design','coordinate'],targets:['society','data','people'],env:{social:4,structure:4,pace:3,place:4,time:5},problem:'사람이 안전하고 편리하게 생활·이동하는 도시 환경을 설계합니다.',tasks:['현황 조사','공간·교통 분석','계획과 협의'],hard:'많은 이해관계와 장기적인 변화를 조정해야 합니다.',majors:['도시공학·교통·지리·행정'],subjects:['사회','수학','과학'],club:'지리·사회문제·도시탐구 성격',source:'일반적 경향'},
    {id:'curator',name:'큐레이터·문화기획자',actions:['research','organize','express'],targets:['content','people','ideas'],env:{social:4,structure:3,pace:3,place:3,time:4},problem:'예술·역사·문화 자료를 의미 있게 구성해 사람과 연결합니다.',tasks:['자료 조사','전시·행사 기획','해설과 홍보'],hard:'예산·공간·관람객 요구를 함께 고려해야 합니다.',majors:['미술사·역사·문화콘텐츠·예술경영'],subjects:['사회','예술','국어'],club:'역사·미술·문화기획 성격',source:'일반적 경향'},
    {id:'librarian',name:'사서·정보서비스 분야',actions:['organize','research','help'],targets:['language','people','ideas'],env:{social:3,structure:5,pace:2,place:1,time:3},problem:'사람이 필요한 정보와 자료를 잘 찾고 활용하도록 돕습니다.',tasks:['자료 분류','정보 탐색 지원','독서·문화 프로그램 운영'],hard:'정확한 분류와 꾸준한 이용자 응대가 필요합니다.',majors:['문헌정보·교육·인문사회'],subjects:['국어','사회','정보'],club:'독서·도서관·정보탐색 성격',source:'자격·채용 경로 추가 확인 필요'},
    {id:'civil',name:'공공행정·공무원 분야',actions:['organize','coordinate','help'],targets:['people','society','data'],env:{social:4,structure:5,pace:3,place:3,time:4},problem:'공공서비스와 제도가 안정적으로 운영되도록 지원합니다.',tasks:['민원·사업 처리','자료와 규정 검토','부서·기관 협업'],hard:'규정 준수와 다양한 요구 조정이 필요합니다.',majors:['행정·정치·경제·다양한 전공'],subjects:['사회','국어','수학'],club:'학생자치·사회문제·봉사 성격',source:'직렬별 공식 정보 확인 필요'},
    {id:'sales',name:'영업·고객 솔루션 분야',actions:['explain','persuade','help'],targets:['people','ideas','machine'],env:{social:5,structure:2,pace:5,place:4,time:1},problem:'고객의 필요를 파악해 적절한 제품이나 해결책을 연결합니다.',tasks:['고객 요구 파악','제품·서비스 설명','관계 관리'],hard:'성과 압박과 거절을 경험할 수 있습니다.',majors:['경영·커뮤니케이션·제품 관련 전공'],subjects:['국어','사회','영어'],club:'토론·창업·학생자치 성격',source:'일반적 경향'},
    {id:'technicalwriter',name:'기술 문서 작성자',actions:['analyze','organize','explain'],targets:['language','machine','ideas'],env:{social:2,structure:5,pace:3,place:1,time:4},problem:'복잡한 기술과 제품 사용법을 정확하고 이해하기 쉽게 설명합니다.',tasks:['기술 내용 이해','매뉴얼·도움말 작성','사용자 피드백 반영'],hard:'정확한 용어와 꾸준한 수정 작업이 필요합니다.',majors:['공학·국어·번역·정보'],subjects:['국어','정보','영어','과학'],club:'과학소통·글쓰기·코딩 성격',source:'일반적 경향'},
    {id:'sciencecomm',name:'과학 커뮤니케이터',actions:['research','explain','express'],targets:['ideas','people','content'],env:{social:4,structure:2,pace:4,place:4,time:2},problem:'과학 지식을 대중이 이해하고 흥미를 느끼도록 전달합니다.',tasks:['과학 자료 조사','강연·영상·전시 기획','오해하기 쉬운 내용 검토'],hard:'정확성과 재미를 동시에 맞춰야 합니다.',majors:['과학계열·교육·미디어'],subjects:['과학','국어','예술','정보'],club:'과학탐구·방송·교육 성격',source:'일반적 경향'},
    {id:'game',name:'게임 기획자',actions:['design','make','coordinate'],targets:['content','people','ideas'],env:{social:4,structure:2,pace:5,place:1,time:4},problem:'사람이 재미있고 몰입할 수 있는 게임 규칙과 경험을 설계합니다.',tasks:['게임 규칙·레벨 기획','개발·디자인 협업','테스트와 밸런스 수정'],hard:'많은 반복 테스트와 일정 압박이 있을 수 있습니다.',majors:['게임·콘텐츠·컴퓨터·디자인'],subjects:['정보','수학','예술','국어'],club:'게임제작·코딩·스토리 성격',source:'일반적 경향'},
    {id:'ai',name:'AI·머신러닝 엔지니어',actions:['research','analyze','make'],targets:['data','ideas','machine'],env:{social:2,structure:4,pace:5,place:1,time:5},problem:'데이터로 학습하는 시스템을 만들고 성능을 개선합니다.',tasks:['데이터 준비','모델 개발','결과 검증과 개선'],hard:'수학·코딩 학습과 빠른 기술 변화 대응이 필요합니다.',majors:['컴퓨터·AI·수학·통계'],subjects:['수학','정보','과학'],club:'코딩·데이터·AI 성격',source:'공식 직업정보 확인 권장'},
    {id:'security',name:'정보보안 전문가',actions:['analyze','research','revise'],targets:['data','machine','society'],env:{social:3,structure:5,pace:5,place:1,time:3},problem:'정보시스템의 위험을 찾고 공격과 사고를 예방합니다.',tasks:['취약점 분석','보안 설정·모니터링','사고 대응과 개선'],hard:'긴장 상황과 지속적인 학습이 필요합니다.',majors:['정보보안·컴퓨터·정보통신'],subjects:['정보','수학','사회'],club:'코딩·보안·정보윤리 성격',source:'공식 직업정보 확인 권장'},
    {id:'quality',name:'품질관리·품질분석가',actions:['compare','analyze','revise'],targets:['machine','data','people'],env:{social:3,structure:5,pace:3,place:3,time:3},problem:'제품과 서비스가 정해진 기준을 안정적으로 만족하도록 관리합니다.',tasks:['검사 기준 설정','오류 원인 분석','개선안 적용'],hard:'작은 문제도 반복적으로 확인하는 꼼꼼함이 필요합니다.',majors:['산업공학·공학·통계·경영'],subjects:['수학','과학','정보'],club:'과학탐구·메이커·데이터 성격',source:'일반적 경향'},
    {id:'hr',name:'인사·조직개발 담당자',actions:['help','analyze','coordinate'],targets:['people','data','ideas'],env:{social:5,structure:4,pace:3,place:1,time:4},problem:'사람이 조직에서 성장하고 협력하도록 제도와 교육을 설계합니다.',tasks:['채용·교육 기획','조직 문제 조사','구성원 상담과 조정'],hard:'공정성과 조직 요구를 함께 고려해야 합니다.',majors:['경영·심리·교육·사회'],subjects:['사회','국어','수학'],club:'학생자치·상담·기획 성격',source:'일반적 경향'},
    {id:'event',name:'행사·공연 기획자',actions:['design','coordinate','express'],targets:['people','content','ideas'],env:{social:5,structure:2,pace:5,place:5,time:2},problem:'사람이 참여하고 기억할 수 있는 행사와 공연을 만듭니다.',tasks:['콘셉트 기획','예산·일정·인력 조정','현장 운영'],hard:'변수가 많고 마감·현장 대응 부담이 큽니다.',majors:['문화기획·예술경영·관광·미디어'],subjects:['예술','사회','국어'],club:'축제·방송·학생자치 성격',source:'일반적 경향'},
    {id:'tourism',name:'관광·여행 기획자',actions:['research','design','coordinate'],targets:['people','society','content'],env:{social:5,structure:3,pace:5,place:5,time:2},problem:'사람이 지역과 문화를 안전하고 의미 있게 경험하도록 여행을 설계합니다.',tasks:['지역·고객 조사','일정·상품 구성','현장 서비스 조정'],hard:'계절·날씨·안전·고객 요구 등 변수가 많습니다.',majors:['관광·문화·경영·지리'],subjects:['사회','영어','국어'],club:'관광·지리·문화탐방 성격',source:'일반적 경향'},
    {id:'agritech',name:'스마트농업·농생명 기술 분야',actions:['research','design','analyze'],targets:['nature','data','machine'],env:{social:3,structure:4,pace:3,place:5,time:5},problem:'기술과 데이터를 활용해 농업 생산과 환경을 개선합니다.',tasks:['생육 관찰','센서·데이터 분석','재배 시스템 개선'],hard:'현장 조건과 생명 주기를 오래 관찰해야 합니다.',majors:['농생명·스마트팜·생명·공학'],subjects:['과학','수학','정보','기술·가정'],club:'생명·환경·로봇·메이커 성격',source:'일반적 경향'},
    {id:'ocean',name:'해양과학·해양기술 분야',actions:['research','analyze','make'],targets:['nature','data','machine'],env:{social:3,structure:4,pace:3,place:5,time:5},problem:'바다의 환경과 자원을 연구하고 안전한 활용 기술을 개발합니다.',tasks:['현장·관측 자료 수집','데이터 분석','장비·기술 개선'],hard:'현장 접근과 장기간 관측이 필요할 수 있습니다.',majors:['해양과학·해양공학·환경'],subjects:['과학','수학','정보'],club:'해양·환경·과학탐구 성격',source:'일반적 경향'},
    {id:'teachertech',name:'컴퓨터·정보 교육 분야',actions:['explain','make','help'],targets:['people','ideas','machine'],env:{social:5,structure:3,pace:4,place:2,time:3},problem:'사람이 디지털 기술을 이해하고 활용하도록 가르칩니다.',tasks:['수업·실습 설계','코딩·정보윤리 지도','학습자료 제작'],hard:'기술 변화에 맞춰 계속 배우고 다양한 수준을 지원해야 합니다.',majors:['컴퓨터교육·정보교육·교육공학'],subjects:['정보','수학','국어'],club:'코딩·교육봉사·미디어 성격',source:'교육·자격 경로 추가 확인 필요'}
  ],
  experiments:[
    {id:'a1',action:'analyze',title:'학교생활 불편 원인 분류',time:'1주',mode:'개인',place:'자율시간',device:'불필요',cost:'0원',output:'데이터',needsPeople:true,steps:['불편한 점을 한 가지 정함','친구 5~10명에게 동의를 받고 의견을 모음','원인을 2~4가지로 분류','가장 큰 원인과 개선안을 한 장으로 정리'],complete:'의견 수집 + 원인 분류 + 개선안 1개',fallback:'본인 경험 3개만 비교해 원인을 분류'},
    {id:'a2',action:'analyze',title:'기사 두 편의 관점 비교',time:'30분',mode:'개인',place:'수업',device:'가능',cost:'0원',output:'이미지',needsPeople:false,steps:['같은 사건을 다룬 기사 2개 선택','제목·자료·표현 차이 표시','왜 차이가 생겼는지 추정','비교표 또는 인포그래픽 제작'],complete:'비교 기준 3개 + 차이 설명',fallback:'교사가 제공한 짧은 기사 2개 사용'},
    {id:'a3',action:'analyze',title:'공개 통계 한 장 해석',time:'1주',mode:'개인',place:'자율시간',device:'필요',cost:'0원',output:'데이터',needsPeople:false,steps:['관심 통계자료 1개 선택','그래프를 다시 그리거나 핵심 수치 표시','눈에 띄는 변화 2개 찾기','가능한 이유와 추가 질문 작성'],complete:'그래프 1개 + 해석 3문장',fallback:'교사가 제공한 표를 손으로 그래프화'},
    {id:'e1',action:'explain',title:'중학생용 한 장 설명자료',time:'1주',mode:'개인',place:'수업',device:'가능',cost:'0원',output:'이미지',needsPeople:true,steps:['교과 개념 1개 선택','중학생이 어려워할 부분 예상','글·그림·예시로 한 장 제작','친구 2명 피드백 후 1회 수정'],complete:'초안 + 피드백 2명 + 수정본',fallback:'친구 피드백 없이 스스로 전후 비교'},
    {id:'e2',action:'explain',title:'글 설명과 그림 설명 비교',time:'30분',mode:'개인',place:'수업',device:'불필요',cost:'0원',output:'글',needsPeople:true,steps:['같은 개념을 글과 그림으로 각각 설명','친구에게 더 이해하기 쉬운 방식 질문','이유 기록','다음 수정 방향 작성'],complete:'두 방식 제작 + 반응 비교',fallback:'본인이 읽어보고 장단점 비교'},
    {id:'e3',action:'explain',title:'친구 질문으로 설명 개선',time:'1주',mode:'개인',place:'자율시간',device:'불필요',cost:'0원',output:'발표',needsPeople:true,steps:['친구가 어려워하는 개념 확인','5분 이내 설명','이해 안 된 부분 질문 받기','설명 방식을 바꾸어 다시 시도'],complete:'1차 설명 + 질문 + 2차 설명',fallback:'예상 질문 3개를 스스로 만들어 수정'},
    {id:'d1',action:'design',title:'교실 물건·공간 개선안',time:'1주',mode:'개인',place:'자율시간',device:'불필요',cost:'0원',output:'제작물',needsPeople:false,steps:['불편한 물건이나 공간 하나 관찰','사용자가 불편한 이유 정리','개선 스케치와 사용 흐름 작성','장단점과 한계 표시'],complete:'문제 정의 + 개선 스케치 + 한계',fallback:'집이나 개인 물건으로 범위 변경'},
    {id:'d2',action:'design',title:'앱 화면 흐름 설계',time:'1주',mode:'개인',place:'자율시간',device:'가능',cost:'0원',output:'이미지',needsPeople:false,steps:['해결할 문제 하나 선택','사용자가 해야 할 행동 순서 작성','화면 3~5개 스케치','친구가 헷갈릴 부분 예상해 수정'],complete:'화면 흐름 3개 이상 + 수정 1회',fallback:'종이에 손그림으로 제작'},
    {id:'d3',action:'design',title:'실험 절차 오류 줄이기',time:'1주',mode:'개인',place:'수업',device:'불필요',cost:'0원',output:'글',needsPeople:false,steps:['기존 실험 절차 선택','오류가 생길 지점 3개 찾기','예방 방법 제안','수정 절차를 흐름도로 정리'],complete:'오류 3개 + 예방안 + 흐름도',fallback:'일상 요리·조립 절차로 변경'},
    {id:'h1',action:'help',title:'신입생 학교생활 안내자료',time:'2~4주',mode:'모둠',place:'동아리',device:'가능',cost:'0원',output:'이미지',needsPeople:true,steps:['신입생이 어려워할 상황 정하기','선생님과 조사 범위 상의','안내 내용 조사','한 장 또는 짧은 카드뉴스 제작'],complete:'안내자료 + 사용 대상 의견 2개',fallback:'본인이 입학 초 궁금했던 점만 정리'},
    {id:'h2',action:'help',title:'또래 학습 불편 해결자료',time:'1주',mode:'개인',place:'자율시간',device:'가능',cost:'0원',output:'글',needsPeople:true,steps:['친구의 동의를 받고 학습 불편 1개 질문','어려움의 원인 추정','짧은 도움자료 제작','도움이 되었는지 확인'],complete:'불편 파악 + 도움자료 + 반응',fallback:'본인의 과거 학습 불편을 대상으로 제작'},
    {id:'h3',action:'help',title:'교내 행사 안내 방식 개선',time:'1주',mode:'모둠',place:'동아리',device:'불필요',cost:'0원',output:'발표',needsPeople:false,steps:['행사 안내문이나 참여 흐름 관찰','처음 참여자가 헷갈릴 부분 찾기','안내 순서·표현 개선','전후 비교'],complete:'문제 2개 + 개선안 + 비교',fallback:'온라인 신청 안내 화면으로 변경'},
    {id:'x1',action:'express',title:'사회문제 인포그래픽',time:'1주',mode:'개인',place:'수업',device:'가능',cost:'0원',output:'이미지',needsPeople:false,steps:['관심 사회문제 1개 선택','신뢰할 자료 2개 찾기','핵심 메시지 1개 정하기','수치·그림·문장으로 한 장 제작'],complete:'출처 2개 + 메시지 1개 + 인포그래픽',fallback:'손그림 포스터로 제작'},
    {id:'x2',action:'express',title:'교과 내용 영상 스토리보드',time:'1주',mode:'개인',place:'수업',device:'불필요',cost:'0원',output:'이미지',needsPeople:false,steps:['교과 개념이나 사건 선택','30~60초 영상 목표 정하기','장면 6칸 구성','설명 문구와 화면 요소 작성'],complete:'6칸 스토리보드 + 핵심 메시지',fallback:'4컷 만화로 축소'},
    {id:'x3',action:'express',title:'같은 메시지 두 방식 표현',time:'30분',mode:'개인',place:'수업',device:'불필요',cost:'0원',output:'글',needsPeople:true,steps:['전달할 메시지 하나 정하기','포스터와 짧은 글로 각각 표현','친구 2명에게 더 잘 전달된 방식 질문','차이와 수정점 기록'],complete:'표현 2종 + 반응 비교',fallback:'본인이 장단점 평가'},
    {id:'c1',action:'coordinate',title:'모둠 역할·일정 운영 실험',time:'1주',mode:'모둠',place:'수업',device:'불필요',cost:'0원',output:'글',needsPeople:true,steps:['작은 모둠 과제 선택','역할과 일정표 작성','중간 점검 1회','실제 문제와 수정 내용을 기록'],complete:'계획표 + 점검 + 수정 기록',fallback:'개인 공부 계획을 3일 운영'},
    {id:'c2',action:'coordinate',title:'행사 진행 흐름 개선',time:'1주',mode:'모둠',place:'동아리',device:'불필요',cost:'0원',output:'발표',needsPeople:false,steps:['작은 행사나 학급 활동 흐름 관찰','대기·혼란 지점 찾기','새 진행 순서 제안','전후 흐름도 비교'],complete:'문제 지점 + 새 흐름도',fallback:'급식·도서대출 등 일상 흐름 관찰'},
    {id:'c3',action:'coordinate',title:'역할 충돌 줄이는 규칙 만들기',time:'30분',mode:'모둠',place:'수업',device:'불필요',cost:'0원',output:'글',needsPeople:true,steps:['모둠에서 생길 수 있는 충돌 3개 예상','예방 규칙 작성','친구 의견 반영','최종 규칙 5개 이내 정리'],complete:'충돌 3개 + 규칙 + 피드백',fallback:'과거 경험을 바탕으로 혼자 작성'},
    {id:'r1',action:'research',title:'관심 주제 자료 신뢰도 비교',time:'1주',mode:'개인',place:'자율시간',device:'필요',cost:'0원',output:'글',needsPeople:false,steps:['관심 주제 자료 3개 찾기','작성자·근거·날짜 확인','신뢰도 차이 정리','가장 믿을 자료와 이유 작성'],complete:'자료 3개 + 판단 기준 3개',fallback:'교사가 제공한 자료 사용'},
    {id:'m1',action:'make',title:'종이 모형으로 아이디어 구현',time:'1주',mode:'개인',place:'자율시간',device:'불필요',cost:'0원',output:'제작물',needsPeople:false,steps:['해결할 불편 하나 선택','종이·재활용품으로 모형 제작','사용 장면을 가정해 문제 찾기','1회 수정'],complete:'초안 모형 + 문제 발견 + 수정',fallback:'스케치와 사용 시나리오로 대체'}
  ],
  config:{
    version:'3.3.0',
    keywordPath:'./keyword.html',
    inactivityMinutes:15,
    maxSubjects:3,
    maxCourses:4
  },
  courseCatalog:[
    {id:'reading_career',name:'독서와 진로',area:'국어',actions:['research','analyze','explain'],targets:['language','ideas','society'],note:'진로 관련 자료를 읽고 근거를 정리하는 활동과 연결'},
    {id:'media',name:'미디어 수용과 제작',area:'국어·미디어',actions:['research','compare','express','make'],targets:['content','language','society'],note:'미디어 분석과 콘텐츠 제작 활동과 연결'},
    {id:'speech',name:'화법과 언어',area:'국어',actions:['explain','persuade','coordinate'],targets:['people','language'],note:'설명·토론·의사소통 활동과 연결'},
    {id:'math_task',name:'수학과제 탐구',area:'수학',actions:['analyze','design','research'],targets:['data','ideas'],note:'수학적 모델링과 문제 해결 탐구에 활용'},
    {id:'ai_math',name:'인공지능 수학',area:'수학·정보',actions:['analyze','design','make'],targets:['data','ideas'],note:'데이터와 알고리즘을 수학적으로 탐색'},
    {id:'data_science',name:'데이터 과학',area:'정보',actions:['research','compare','analyze'],targets:['data','society'],note:'데이터 수집·분석·시각화 활동과 연결'},
    {id:'software',name:'소프트웨어와 생활',area:'정보',actions:['design','make','revise'],targets:['ideas','machine','data'],note:'생활 문제를 소프트웨어로 해결하는 활동과 연결'},
    {id:'robot',name:'로봇과 공학세계',area:'기술·공학',actions:['design','make','revise'],targets:['machine','data'],note:'기계·전자·제어와 제작 활동에 활용'},
    {id:'physics',name:'물리학',area:'과학',actions:['analyze','design','research'],targets:['machine','nature','data'],note:'힘·에너지·운동·전자기 현상 탐구'},
    {id:'chemistry',name:'화학',area:'과학',actions:['research','analyze','revise'],targets:['nature','data'],note:'물질 변화와 실험·분석 활동에 활용'},
    {id:'biology',name:'생명과학',area:'과학',actions:['research','analyze','help'],targets:['nature','people','data'],note:'생명 현상과 건강·환경 문제 탐구'},
    {id:'earth',name:'지구과학',area:'과학',actions:['research','analyze','compare'],targets:['nature','data','society'],note:'지구 환경과 관측 자료 분석'},
    {id:'society',name:'사회문제 탐구',area:'사회',actions:['research','compare','analyze','persuade'],targets:['society','people','data'],note:'사회문제의 원인과 대안을 탐구'},
    {id:'ethics',name:'윤리문제 탐구',area:'사회·윤리',actions:['analyze','compare','persuade'],targets:['society','ideas','people'],note:'가치 갈등과 판단 근거를 탐색'},
    {id:'economy',name:'경제',area:'사회',actions:['analyze','compare','research'],targets:['data','society','people'],note:'시장과 선택, 사회 현상을 자료로 분석'},
    {id:'politics',name:'정치',area:'사회',actions:['research','analyze','persuade'],targets:['society','people','language'],note:'정책·제도·시민 참여와 연결'},
    {id:'psychology',name:'인간과 심리',area:'교양·사회',actions:['research','help','analyze'],targets:['people','ideas','data'],note:'사람의 행동과 마음을 탐색'},
    {id:'education',name:'교육의 이해',area:'교양',actions:['explain','help','design'],targets:['people','ideas'],note:'학습과 교육 활동을 이해하고 설계'},
    {id:'art_design',name:'미술 창작·디자인',area:'예술',actions:['express','design','make','revise'],targets:['content','ideas','people'],note:'시각 표현과 디자인 제작 활동에 활용'},
    {id:'music_media',name:'음악·영상 제작',area:'예술',actions:['express','make','coordinate'],targets:['content','people'],note:'소리와 영상으로 메시지를 제작'},
    {id:'sports_science',name:'스포츠 과학',area:'체육',actions:['analyze','research','revise'],targets:['people','data','nature'],note:'운동 수행과 건강을 자료로 탐색'},
    {id:'environment_course',name:'기후변화와 지속가능한 세계',area:'융합',actions:['research','analyze','persuade'],targets:['nature','society','data'],note:'환경 문제와 지속가능성 탐구'},
    {id:'entrepreneurship',name:'창업과 지식재산',area:'융합·진로',actions:['design','make','persuade','coordinate'],targets:['people','ideas','content'],note:'문제 발견·아이디어 구현·협업과 연결'}
  ],
  galleryExamples:[
    {id:'g1',status:'가상 예시',title:'중학생용 과학 개념 한 장 설명서',action:'explain',targets:['people','ideas'],duration:'1주',summary:'통합과학 개념 하나를 그림과 비유로 설명하고 친구 피드백을 받아 수정함.',result:'초안 1장, 피드백 3명, 수정본 1장',reflection:'설명 자체는 재미있었지만 다른 사람이 이해하지 못한 부분을 고치는 일이 더 중요했음을 알게 됨.'},
    {id:'g2',status:'가상 예시',title:'학급 설문 데이터 시각화',action:'analyze',targets:['data','society'],duration:'1주',summary:'학급 생활 주제의 익명 설문을 받아 표와 그래프로 정리하고 의미를 설명함.',result:'응답표, 그래프 3개, 해석문',reflection:'숫자를 정리하는 것은 재미있었지만 질문을 공정하게 만드는 일이 어려웠음.'},
    {id:'g3',status:'가상 예시',title:'교실 물건 개선안 스케치',action:'design',targets:['machine','people'],duration:'30분',summary:'교실에서 불편한 물건 하나를 정하고 사용 장면을 관찰해 개선안을 그림으로 제안함.',result:'문제 장면, 개선 스케치, 사용 설명',reflection:'새 아이디어를 내는 것보다 실제 사용 조건을 고려하는 일이 더 어려웠음.'},
    {id:'g4',status:'가상 예시',title:'신입생 학교생활 안내 카드',action:'help',targets:['people','content'],duration:'1주',summary:'신입생이 어려워할 내용을 인터뷰 없이 가정하지 않고 교내 안내 자료를 확인해 카드로 제작함.',result:'안내 카드 5장, 교사 검토 1회',reflection:'돕는 마음만으로는 부족하고 정확한 정보를 확인해야 함을 배움.'},
    {id:'g5',status:'가상 예시',title:'같은 사건 기사 관점 비교',action:'research',targets:['language','society'],duration:'30분',summary:'같은 사건을 다룬 기사 두 편에서 제목, 자료, 인용 대상의 차이를 비교함.',result:'비교표 1개, 질문 2개',reflection:'어느 한쪽이 무조건 틀렸다기보다 선택한 정보가 판단에 영향을 줄 수 있음을 알게 됨.'},
    {id:'g6',status:'가상 예시',title:'모둠 역할 충돌 줄이기 규칙',action:'coordinate',targets:['people','ideas'],duration:'1주',summary:'모둠 과제의 역할과 중간 점검 시점을 정하고 실제 진행 중 한 번 수정함.',result:'역할표, 점검 기록, 수정 규칙',reflection:'계획을 세우는 것보다 서로의 진행 상황을 확인하고 바꾸는 일이 중요했음.'}
  ]

};
