(()=>{'use strict';const F=window.FLOW;F.mountNav('inquiry');const $=id=>document.getElementById(id);let method='compare';
const methods=[['compare','자료 비교','기사·문헌·사례를 같은 기준으로 비교','자료 2개 이상과 비교 기준이 필요합니다.'],['survey','설문·인터뷰','사람의 경험·인식·요구를 조사','동의와 익명 처리, 편향 없는 질문이 중요합니다.'],['data','공개 데이터 분석','통계·수치 자료를 표와 그래프로 분석','출처와 단위, 표본 범위를 확인합니다.'],['experiment','실험·관찰','조건을 바꾸거나 반복 관찰해 차이를 확인','변인을 통제하고 반복 기록합니다.'],['design','제작·사용자 검증','해결안·콘텐츠·모형을 만들고 피드백으로 개선','사용 기준과 수정 전후를 기록합니다.'],['content','텍스트·콘텐츠 분석','글·영상·이미지의 표현과 의미를 분류','분류 기준을 먼저 정하고 근거를 남깁니다.']];
const val=id=>$(id).value.trim();
function renderMethods(){$('methodCards').innerHTML=methods.map(([id,n,d])=>`<button type="button" class="choice-card ${method===id?'selected':''}" data-method="${id}"><strong>${n}</strong><small>${d}</small></button>`).join('');document.querySelectorAll('[data-method]').forEach(b=>b.onclick=()=>{method=b.dataset.method;renderMethods();showGuide()});showGuide()}
function showGuide(){const m=methods.find(x=>x[0]===method);$('methodGuide').innerHTML=`<strong>${m[1]}</strong> — ${m[3]}`}
function summary(p){return `<dl><dt>탐구 질문</dt><dd>${F.esc(p.question)}</dd><dt>목적</dt><dd>${F.esc(p.purpose)}</dd><dt>방법</dt><dd>${F.esc(methods.find(x=>x[0]===p.method)?.[1]||p.method)}</dd><dt>대상</dt><dd>${F.esc(p.target)}</dd><dt>자료</dt><dd>${F.esc(p.sources)}</dd><dt>절차</dt><dd>${F.esc(p.procedure)}</dd><dt>일정</dt><dd>${F.esc(p.schedule)}</dd><dt>결과물</dt><dd>${F.esc(p.output)}</dd><dt>검증</dt><dd>${F.esc(p.verification)}</dd><dt>한계</dt><dd>${F.esc(p.limits)}</dd></dl>`}
function payload(){return{version:1,createdAt:new Date().toISOString(),question:val('question'),purpose:val('purpose'),expectation:val('expectation'),method,target:val('target'),sources:val('sources'),procedure:val('procedure'),roles:val('roles'),schedule:val('schedule'),output:$('output').value,criteria:val('criteria'),verification:val('verification'),limits:val('limits'),ethics:val('ethics'),checks:{time:$('cTime').checked,data:$('cData').checked,method:$('cMethod').checked,ethics:$('cEthics').checked,revise:$('cRevise').checked},keyword:F.read(F.keys.keyword)}}
function text(p){return `탐구 설계안\n- 질문: ${p.question}\n- 목적: ${p.purpose}\n- 예상: ${p.expectation}\n- 방법: ${methods.find(x=>x[0]===p.method)?.[1]}\n- 대상: ${p.target}\n- 자료: ${p.sources}\n- 절차: ${p.procedure}\n- 역할: ${p.roles}\n- 일정: ${p.schedule}\n- 결과물: ${p.output}\n- 판단 기준: ${p.criteria}\n- 검증 방법: ${p.verification}\n- 한계: ${p.limits}\n- 윤리·개인정보: ${p.ethics}`}
function save(go=false){const p=payload();if(!p.question||!p.purpose||!p.target||!p.sources||!p.procedure)return F.setStatus('inquiryMessage','질문·목적·대상·자료·절차를 작성하세요.','warning');if(!Object.values(p.checks).every(Boolean))return F.setStatus('inquiryMessage','실행 가능성 점검 항목을 모두 확인하세요.','warning');F.write(F.keys.inquiry,p);$('printSummary').innerHTML=summary(p);F.setStatus('inquiryMessage','탐구 설계를 저장했습니다.','info');if(go)location.href='roadmap.html'}
$('saveInquiry').onclick=()=>save(false);$('goRoadmap').onclick=()=>save(true);$('copyInquiry').onclick=()=>F.copy(text(payload()),'탐구 설계안을 복사했습니다.');$('printInquiry').onclick=()=>{save(false);window.print()};$('clearFlow').onclick=()=>{if(confirm('연계 자료를 모두 삭제할까요?')){F.removeAll();location.reload()}};
const k=F.read(F.keys.keyword),s=F.read(F.keys.inquiry);F.setStatus('sourceStatus',k?'저장된 탐구 질문을 불러왔습니다.':'질문 자료가 없습니다. 질문을 직접 입력하거나 STEP 1부터 진행하세요.',k?'info':'warning');if(s){['question','purpose','expectation','target','sources','procedure','roles','schedule','criteria','verification','limits','ethics'].forEach(id=>$(id).value=s[id]||'');$('output').value=s.output||'탐구 보고서';method=s.method||'compare';Object.entries(s.checks||{}).forEach(([k,v])=>{const id={time:'cTime',data:'cData',method:'cMethod',ethics:'cEthics',revise:'cRevise'}[k];if(id)$(id).checked=!!v});$('printSummary').innerHTML=summary(s)}else if(k){$('question').value=k.question||'';$('purpose').value=k.reason||'';$('target').value=k.scope?.target||'';$('sources').value=k.scope?.data||'';$('schedule').value=[k.scope?.place,k.scope?.time].filter(Boolean).join(' / ');$('criteria').value=k.scope?.variable||''}renderMethods();})();
