(()=>{'use strict';const F=window.FLOW;F.mountNav('keyword');
const $=id=>document.getElementById(id);const bridge=()=>F.read(F.keys.bridge)||{};let selectedType='compare';
const types=[['compare','비교하기','두 대상·방법·자료의 차이를 확인'],['cause','원인 찾기','어떤 현상이 나타나는 이유를 확인'],['effect','영향 확인','한 요소가 다른 결과에 미치는 영향'],['status','현황 파악','현재 상태·경향·분포를 확인'],['design','개선·설계','문제를 줄이기 위한 방법을 만들고 검토'],['meaning','의미 해석','자료·표현·사례가 가진 의미를 분석']];
function labelList(v){return Array.isArray(v)?v.join(', '):(v||'')}
function showBridge(){const b=bridge();const has=Object.keys(b).length>0;F.setStatus('bridgeStatus',has?'STEP 0의 진로 가설 자료를 불러왔습니다. 필요한 부분만 질문 씨앗으로 사용하세요.':'연계 자료가 없습니다. 이 페이지에서 직접 주제를 입력해도 됩니다.',has?'info':'warning');$('bridgeSummary').innerHTML=has?`<dl><dt>관심 행동</dt><dd>${F.esc(labelList(b.approvedActions)||'없음')}</dd><dt>관심 대상</dt><dd>${F.esc(labelList(b.targets)||'없음')}</dd><dt>비교 직업</dt><dd>${F.esc(b.jobGroup||'없음')}</dd><dt>미니 실험</dt><dd>${F.esc(b.experiment||'없음')}</dd><dt>기존 질문 씨앗</dt><dd>${F.esc(b.questionSeed||'없음')}</dd><dt>아직 불확실한 점</dt><dd>${F.esc(b.unknown||'없음')}</dd></dl>`:'<div class="empty-state">진로 실험실을 먼저 마치거나 직접 주제를 입력하세요.</div>';if(has&&!$('topic').value)$('topic').value=b.questionSeed||b.experiment||b.jobGroup||'';if(has&&!$('reason').value)$('reason').value=[b.coreAction&&`내가 실제로 한 핵심 행동은 ${b.coreAction}이었다.`,b.unknown&&`아직 ${b.unknown}을 확인하지 못했다.`].filter(Boolean).join(' ')}
function renderTypes(){$('questionTypes').innerHTML=types.map(([id,n,d])=>`<button type="button" class="choice-card ${selectedType===id?'selected':''}" data-qtype="${id}"><strong>${n}</strong><small>${d}</small></button>`).join('');document.querySelectorAll('[data-qtype]').forEach(b=>b.onclick=()=>{selectedType=b.dataset.qtype;renderTypes();make()})}
const v=id=>$(id).value.trim();
function candidates(){const t=v('topic')||'관심 현상',a=v('scopeTarget'),p=v('scopePlace'),tm=v('scopeTime'),x=v('scopeVariable'),d=v('scopeData');const scope=[a,p,tm].filter(Boolean).join('·');const where=scope?`${scope}에서 `:'';const by=d?`${d}을 활용하여 `:'';const criterion=x||'주요 차이';const map={compare:[`${where}${t}은(는) 비교 대상에 따라 어떤 차이를 보이는가?`,`${by}${t}의 차이를 ${criterion}을 중심으로 어떻게 설명할 수 있는가?`,`${where}${t}을(를) 두 방식으로 비교했을 때 공통점과 차이점은 무엇인가?`],cause:[`${where}${t}이(가) 나타나는 주요 원인은 무엇인가?`,`${by}${t}의 원인을 ${criterion}을 중심으로 어떻게 설명할 수 있는가?`,`${where}${t}에 영향을 주는 요인들은 서로 어떤 관계가 있는가?`],effect:[`${where}${criterion}은(는) ${t}에 어떤 영향을 미치는가?`,`${by}${criterion}의 변화에 따라 ${t}은(는) 어떻게 달라지는가?`,`${where}${t}에 미치는 ${criterion}의 영향은 어떤 조건에서 더 크게 나타나는가?`],status:[`${where}${t}의 현재 모습과 주요 경향은 어떠한가?`,`${by}${t}의 현황을 ${criterion}에 따라 분류하면 어떤 특징이 나타나는가?`,`${where}${t}은(는) 시간이나 집단에 따라 어떻게 분포하는가?`],design:[`${where}${t}을(를) 개선하기 위한 방법은 무엇이며 실제 적용 시 어떤 변화가 나타나는가?`,`${criterion}을 고려한 ${t} 개선안을 어떻게 설계하고 평가할 수 있는가?`,`${by}${t}의 문제를 줄이기 위한 해결안을 만들고 그 효과를 어떻게 확인할 수 있는가?`],meaning:[`${where}${t}에 나타난 표현이나 자료는 어떤 의미를 가지는가?`,`${by}${t}을(를) ${criterion}의 관점에서 해석하면 무엇을 알 수 있는가?`,`${where}${t}의 사례들은 어떤 공통된 의미와 차이를 보여주는가?`]};return map[selectedType]}
function make(){$('questionCandidates').innerHTML=candidates().map((q,i)=>`<label class="candidate-card"><input type="radio" name="candidate" value="${F.esc(q)}"><span><strong>후보 ${i+1}</strong><br>${F.esc(q)}</span></label>`).join('');document.querySelectorAll('input[name=candidate]').forEach(r=>r.onchange=()=>{$('finalQuestion').value=r.value})}
function payload(){return{version:1,createdAt:new Date().toISOString(),topic:v('topic'),reason:v('reason'),type:selectedType,scope:{target:v('scopeTarget'),place:v('scopePlace'),time:v('scopeTime'),variable:v('scopeVariable'),data:v('scopeData')},question:v('finalQuestion'),checks:{specific:$('checkSpecific').checked,evidence:$('checkEvidence').checked,open:$('checkOpen').checked},sourceBridge:bridge()}}
function save(go=false){if(!v('topic'))return F.setStatus('keywordMessage','중심 주제를 입력하세요.','warning');if(!v('finalQuestion'))return F.setStatus('keywordMessage','질문 후보를 선택하거나 직접 작성하세요.','warning');if(![$('checkSpecific'),$('checkEvidence'),$('checkOpen')].every(x=>x.checked))return F.setStatus('keywordMessage','좋은 질문 확인 항목 3개를 모두 점검하세요.','warning');F.write(F.keys.keyword,payload());F.setStatus('keywordMessage','탐구 질문을 저장했습니다.','info');if(go)location.href='inquiry.html'}
$('loadBridge').onclick=showBridge;$('makeQuestions').onclick=make;$('saveKeyword').onclick=()=>save(false);$('goInquiry').onclick=()=>save(true);$('copyKeyword').onclick=()=>F.copy(v('finalQuestion'),'탐구 질문을 복사했습니다.');$('clearFlow').onclick=()=>{if(confirm('진로·질문·탐구 연계 자료를 모두 삭제할까요?')){F.removeAll();location.reload()}};
const saved=F.read(F.keys.keyword);if(saved){$('topic').value=saved.topic||'';$('reason').value=saved.reason||'';selectedType=saved.type||'compare';Object.entries(saved.scope||{}).forEach(([k,val])=>{const map={target:'scopeTarget',place:'scopePlace',time:'scopeTime',variable:'scopeVariable',data:'scopeData'};if($(map[k]))$(map[k]).value=val||''});$('finalQuestion').value=saved.question||'';$('checkSpecific').checked=!!saved.checks?.specific;$('checkEvidence').checked=!!saved.checks?.evidence;$('checkOpen').checked=!!saved.checks?.open}showBridge();renderTypes();make();})();
