(()=>{
'use strict';
const F=window.FLOW;F.mountNav('submission');const $=id=>document.getElementById(id);const v=id=>$(id).value.trim();
const labels={bridge:'진로 가설·미니 실험',keyword:'탐구 질문',inquiry:'탐구 설계',roadmap:'성장 로드맵'};
function sources(){return{bridge:F.read(F.keys.bridge),keyword:F.read(F.keys.keyword),inquiry:F.read(F.keys.inquiry),roadmap:F.read(F.keys.roadmap)}}
function join(arr){return(Array.isArray(arr)?arr:[]).filter(Boolean).join(', ')}
function sourceText(){const s=sources(),b=s.bridge||{},k=s.keyword||{},i=s.inquiry||{},r=s.roadmap||{};return{
 motivation:[b.questionSeed&&`처음 떠올린 질문은 '${b.questionSeed}'이었음.`,k.reason,k.topic&&`관심 주제는 '${k.topic}'임.`].filter(Boolean).join(' '),
 actualActivity:[b.experiment&&`진로 미니 실험으로 '${b.experiment}'을 선택함.`,join(b.approvedActions)&&`경험에서 반복된 행동은 ${join(b.approvedActions)}임.`,i.procedure,r.year1?.action].filter(Boolean).join(' '),
 methodsEvidence:[i.method&&`탐구 방법 코드: ${i.method}.`,i.sources&&`활용 자료: ${i.sources}.`,i.target&&`탐구 대상: ${i.target}.`,r.year1?.evidence].filter(Boolean).join(' '),
 challenge:[i.limits,b.unknown].filter(Boolean).join(' '),
 feedbackRevision:[i.verification&&`확인·검증 계획: ${i.verification}.`,r.principles?.feedback?'피드백과 반영 내용을 기록하기로 함.':''].filter(Boolean).join(' '),
 learningChange:[b.coreAction&&`나의 핵심 행동을 '${b.coreAction}'으로 정리함.`,b.change,k.question&&`최종 탐구 질문은 '${k.question}'임.`,r.year3?.story].filter(Boolean).join(' '),
 nextStep:[r.milestones?.next2weeks,r.milestones?.thisSemester,k.question].filter(Boolean).join(' '),
 evidenceList:[r.year1?.evidence,i.output&&`예정 결과물: ${i.output}`,i.criteria&&`판단 기준: ${i.criteria}`].filter(Boolean).join(' / ')
}}
function renderSources(){const s=sources();$('sourceChecklist').innerHTML=Object.entries(labels).map(([key,label])=>`<div class="source-item ${s[key]?'ready':'missing'}"><span>${s[key]?'✓':'!'}</span><div><strong>${label}</strong><small>${s[key]?'저장된 자료를 불러옴':'저장 자료 없음 — 직접 작성 가능'}</small></div></div>`).join('');const count=Object.values(s).filter(Boolean).length;F.setStatus('submissionStatus',`${count}/4단계의 누적 자료를 확인했습니다. 자동 초안은 반드시 실제 활동에 맞게 수정하세요.`,count>=3?'info':'warning')}
function fillDraft(force=false){const d=sourceText();Object.entries(d).forEach(([id,text])=>{if(force||!v(id))$(id).value=text});if(force||!v('submissionTitle'))$('submissionTitle').value='나의 경험에서 시작한 진로 탐구·성장 기록';renderPreview(payload())}
function payload(){return{kind:'career-lab-final-submission-v1',version:1,createdAt:new Date().toISOString(),student:{classInfo:v('classInfo'),studentKey:v('studentKey')},activityPeriod:v('activityPeriod'),title:v('submissionTitle'),record:{motivation:v('motivation'),actualActivity:v('actualActivity'),methodsEvidence:v('methodsEvidence'),challenge:v('challenge'),feedbackRevision:v('feedbackRevision'),learningChange:v('learningChange'),nextStep:v('nextStep'),evidenceList:v('evidenceList')},checks:{actual:$('cActual').checked,noPrivate:$('cNoPrivate').checked,evidence:$('cEvidence').checked,teacher:$('cTeacher').checked},sources:sources()}}
function clean(s){return s||'미작성'}
function text(p){return `${p.title||'진로 탐구·성장 기록'}\n\n[제출 정보]\n학년·반: ${clean(p.student.classInfo)}\n학번/개인코드: ${clean(p.student.studentKey)}\n활동 기간: ${clean(p.activityPeriod)}\n\n[1. 활동을 시작한 계기와 관심 문제]\n${clean(p.record.motivation)}\n\n[2. 실제로 수행한 핵심 활동과 나의 역할]\n${clean(p.record.actualActivity)}\n\n[3. 활용한 자료·방법·도구]\n${clean(p.record.methodsEvidence)}\n\n[4. 어려움·예상과 달랐던 점]\n${clean(p.record.challenge)}\n\n[5. 피드백을 받고 수정한 내용]\n${clean(p.record.feedbackRevision)}\n\n[6. 활동을 통해 알게 된 점과 진로 생각의 변화]\n${clean(p.record.learningChange)}\n\n[7. 다음에 이어갈 질문 또는 실천]\n${clean(p.record.nextStep)}\n\n[8. 교사가 확인할 수 있는 결과물·증거]\n${clean(p.record.evidenceList)}\n\n※ 학생 자기기록 자료이며, 최종 학생부 기록은 교사가 실제 활동과 증거를 확인한 뒤 작성합니다.`}
function renderPreview(p){$('submissionPreview').innerHTML=`<h3>${F.esc(p.title||'진로 탐구·성장 기록')}</h3><p class="submission-meta"><strong>학년·반</strong> ${F.esc(clean(p.student.classInfo))} · <strong>학번/코드</strong> ${F.esc(clean(p.student.studentKey))} · <strong>기간</strong> ${F.esc(clean(p.activityPeriod))}</p>${Object.entries({motivation:'활동 계기와 관심 문제',actualActivity:'핵심 활동과 역할',methodsEvidence:'자료·방법·도구',challenge:'어려움과 예상 밖의 점',feedbackRevision:'피드백과 수정',learningChange:'배움과 진로 생각의 변화',nextStep:'다음 질문·실천',evidenceList:'확인 가능한 결과물·증거'}).map(([k,l])=>`<section><h4>${l}</h4><p>${F.esc(clean(p.record[k])).replace(/\n/g,'<br>')}</p></section>`).join('')}<p class="submission-disclaimer">학생 자기기록 자료이며, 최종 학생부 기록은 교사가 실제 활동과 증거를 확인한 뒤 작성합니다.</p>`}
function validate(p){if(!p.student.studentKey)return'학번 또는 개인코드를 입력하세요.';if(!p.title)return'제출 제목을 입력하세요.';const required=['motivation','actualActivity','learningChange','nextStep','evidenceList'];if(required.some(k=>!p.record[k]))return'활동 계기·핵심 활동·배움과 변화·다음 단계·결과물 증거를 작성하세요.';if(!Object.values(p.checks).every(Boolean))return'제출 전 사실 확인 네 항목을 모두 확인하세요.';return''}
function save(){const p=payload(),err=validate(p);if(err){F.setStatus('submissionMessage',err,'warning');return null}F.write(F.keys.submission,p);renderPreview(p);F.setStatus('submissionMessage','최종 제출 기록을 이 기기에 저장했습니다. 과제방 제출용 파일을 내려받으세요.','info');return p}
function fileBase(p){const key=(p.student.studentKey||'student').replace(/[^0-9A-Za-z가-힣_-]/g,'_');return `진로실험실_최종제출_${key}`}
function downloadText(content,name,type='text/plain;charset=utf-8'){const blob=new Blob(['\ufeff',content],{type}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=name;document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),500)}
function htmlDoc(p){const body=$('submissionPreview').innerHTML;return `<!doctype html><html lang="ko"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${F.esc(p.title)}</title><style>body{font-family:system-ui,"Noto Sans KR",sans-serif;line-height:1.65;color:#172033;max-width:850px;margin:40px auto;padding:0 24px}h1{border-bottom:3px solid #2457d6;padding-bottom:12px}h3{font-size:1.8rem}h4{margin:24px 0 6px;color:#2457d6}.submission-meta{background:#f3f6fb;padding:12px;border-radius:10px}.submission-disclaimer{margin-top:32px;padding:12px;border:1px solid #e2bd68;background:#fff8e7;border-radius:10px;font-size:.9rem}@media print{body{margin:0;max-width:none}}</style></head><body><h1>진로 실험실 최종 활동 기록</h1>${body}</body></html>`}
$('refreshDraft').onclick=()=>{if(confirm('현재 누적 자료를 기준으로 작성란을 다시 채울까요? 직접 수정한 내용은 바뀔 수 있습니다.'))fillDraft(true)};
$('saveSubmission').onclick=save;$('copySubmission').onclick=()=>F.copy(text(payload()),'과제방 제출 내용을 복사했습니다.');
$('downloadTxt').onclick=()=>{const p=save();if(p)downloadText(text(p),`${fileBase(p)}.txt`)};
$('downloadJson').onclick=()=>{const p=save();if(p)F.download(p,`${fileBase(p)}.json`)};
$('downloadHtml').onclick=()=>{const p=save();if(p)downloadText(htmlDoc(p),`${fileBase(p)}.html`,'text/html;charset=utf-8')};
$('printSubmission').onclick=()=>{const p=save();if(p)window.print()};
$('clearFlow').onclick=()=>{if(confirm('진로 실험실의 연계 자료와 최종 제출 기록을 모두 삭제할까요?')){F.removeAll();location.reload()}};
['classInfo','studentKey','activityPeriod','submissionTitle','motivation','actualActivity','methodsEvidence','challenge','feedbackRevision','learningChange','nextStep','evidenceList'].forEach(id=>$(id).addEventListener('input',()=>renderPreview(payload())));
const saved=F.read(F.keys.submission);if(saved){$('classInfo').value=saved.student?.classInfo||'';$('studentKey').value=saved.student?.studentKey||'';$('activityPeriod').value=saved.activityPeriod||'';$('submissionTitle').value=saved.title||'';Object.entries(saved.record||{}).forEach(([k,val])=>{if($(k))$(k).value=val||''});Object.entries(saved.checks||{}).forEach(([k,val])=>{const map={actual:'cActual',noPrivate:'cNoPrivate',evidence:'cEvidence',teacher:'cTeacher'};if(map[k])$(map[k]).checked=!!val});renderPreview(saved)}else fillDraft(false);renderSources();
})();
